### ISSUE TITLE
Implement splitlines method of the FmtStr class

### ISSUE THREAD

**Issue by ata2001** [bpython/curtsies#101]
splitline on a FmtStr does not work as expected. It does split the string by newline characters, but it loses the formatting.

```
>>> from curtsies import fmtstr
>>> from curtsies.fmtfuncs import red
>>> f = fmtstr(red('line0')+'\n'+red('line1'))
>>> f.splitlines()
['line0', 'line1']
```

https://docs.python.org/3.6/library/stdtypes.html#str.splitlines

**Comment by thomasballinger** [comment]
Whoops, totally! Thanks for taking this on, feel free to ping me again if I'm this slow again.

**Comment by thomasballinger** [comment]
Or if we need a release

**Comment by thomasballinger** [comment]
Sorry I've been out of this a bit

**Comment by thomasballinger** [comment]
Thanks for fixing @ata2001
