### ISSUE TITLE
Ctrl-s and Ctrl-q don't work

### ISSUE THREAD

**Issue by georgek** [bpython/curtsies#115]
These two keys correspond to "Pause transmission" and "Resume transmission" (https://en.wikipedia.org/wiki/Software_flow_control). Ctrl-s has the effect of completely freezing the input until Ctrl-q is pressed. Is there any way to stop this and actually receive these key presses into the program?

**Comment by thomasballinger** [comment]
Yep, you want to put something like
```
# Prevent ctrl-s from freezing terminal on some unix terminals
stty stop undef
```
in your `.profile` or `.bashrc` or similar. I don't know what you need for ctrl-q?

**Comment by georgek** [comment]
Is this the only way to disable it? Maybe this should be documented under the notes or common confusions section if that's the case. I wasn't sure if there some way for an application to disable it itself. Are there any other keys that are likely to be intercepted by the terminal?

**Comment by thomasballinger** [comment]
We absolutely could disable this - it'd be with context manager like https://github.com/bpython/curtsies/blob/85831934553f60fbb0783df880cb01ef7e1efad5/curtsies/input.py#L78 and I think it could be done by shelling out to stty or by setting `termios.tcgetattr(self.in_stream)[-1][termios.VSTOP] = 0`

This seems like a reasonable thing to make configurable in Curtsies - I imagine it would not be a default in bpython though, as some people actually use these. I'd be mildly in favor of doing this, but don't use these features and would defer to other maintainers here. If there's an example of another terminal application that does this that makes it easier to justify.

**Comment by georgek** [comment]
Cool, that with the addition of `attrs[-1][termios.VSTART] = 0` does "enable" Ctrl-s and Ctrl-q again in my application. This works either in the `__enter__` method as suggested or in user code by accessing the `in_stream` of the input generator. It would be nicer to be hidden away inside Curtsies :)

**Comment by thomasballinger** [comment]
Try `stty -a` for a list of potential keys that might be intercepted - being in raw mode mode stops most of these, but another one known to stay on is ctrl-y on macs.

**Comment by thomasballinger** [comment]
This could be added as yet another optional arg in `Input.__init__` https://github.com/bpython/curtsies/blob/master/curtsies/input.py#L45 with a name like "disable_terminal_start_stop" that defaulted to false

**Comment by georgek** [comment]
Other ones which seem to get intercepted are Ctrl-?, Ctrl-\ and Ctrl-z. The last is interesting as well because my application becomes broken after Ctrl-z then `fg`.

**Comment by thomasballinger** [comment]
If you want to make ctrl-z suspend work, might be interesting to take a look at how bpython does this: https://github.com/bpython/bpython/blob/master/bpython/curtsiesfrontend/repl.py#L570

**Comment by thomasballinger** [comment]
closing this, feel free to make new issues for other keys, although we might approach them differently.
