### ISSUE TITLE
Unhandled keys in input

### ISSUE THREAD

**Issue by alethiophile** [bpython/curtsies#119]
I was playing with curtsies.events and found some keys it didn't handle (shift and alt with arrow keys). It asked me to report them here, so here they are.

keylog.txt:

```
b'\x1b[1;3C' is called Alt-Right
b'\x1b[1;2C' is called Shift-Right
b'\x1b[1;2B' is called Shift-Down
b'\x1b[1;2D' is called Shift-Left
b'\x1b[1;2A' is called shift-up
b'\x1b[1;3B' is called alt-down
b'\x1b[1;3D' is called alt-left
b'\x1b[1;3A' is called alt-up
```

**Comment by alethiophile** [comment]
Some more unhandled:

```
b'\x1b[3;2~' is called shift-delete
b'\x1b[1;2H' is called shift-home
b'\x1b[1;2F' is called shift-end
b'\x1b[5;2~' is called shift-pageup
b'\x1b[6;2~' is called shift-pagedown
b'\x1b[5;3~' is called alt-pageup
b'\x1b[6;3~' is called alt-pagedown
b'\x1b[1;3H' is called alt-home
b'\x1b[1;3F' is called alt-end
```

My terminal doesn't want to register alt-delete for some reason (I assume it's bound in the emulator or something), but pattern recognition suggests it would also confuse curtsies.

**Comment by thomasballinger** [comment]
Thanks @alethiophile! Do you remember what keyboard, operating system, and terminal emulator this might have been using?

**Comment by thomasballinger** [comment]
see #136

**Comment by alethiophile** [comment]
This should be from gnome-terminal running on Fedora (in a Qubes Xen container), keyboard is a UHK (https://uhk.io).

**Comment by thomasballinger** [comment]
Resolved by https://github.com/bpython/curtsies/pull/136
